--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MrEcstsy/advancedAbilities
build-by-default: true
branches:
- main
projects:
  advancedAbilities:
    path: ""
  AdvancedAbilities:
    path: ""
    type: library
    model: virion
...

